### ISSUE TITLE
The re no default admin login credentials

### ISSUE THREAD

**Issue by matatashadrack** [chetans9/codeigniter-ecommerce#2]

**Comment by chetans9** [comment]
email : admin@admin.com
passwd : chetan

**Comment by alexholz** [comment]
> email : [admin@admin.com](mailto:admin@admin.com)
> passwd : chetan

Hi,

Thank you for your excellent work!!!

I tried those credentials and didn't worked. I tried to add an user direct to the database and didn't worked too.

Any ideas?

Cheers,

Alex

**Comment by alexholz** [comment]
> > email : [admin@admin.com](mailto:admin@admin.com)
> > passwd : chetan
> 
> Hi,
> 
> Thank you for your excellent work!!!
> 
> I tried those credentials and didn't worked. I tried to add an user direct to the database and didn't worked too.
> 
> Any ideas?
> 
> Cheers,
> 
> Alex

I saw you use md5 encryption. When I created in database adding a record with md5 password, worked.

Thank you once more for your great work!!!
